name: dmpr-dev

channels:
    - conda-forge
    - defaults

dependencies:
    - python
    - pbr
    - netcdf4
    - iris
    - sphinx
    - pytest
    - beautifulsoup4
    - tabulate
    - click
    - compliance-checker
    - xarray
